# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protoBusqueda_pb2 as protoBusqueda__pb2


class ServicioBusquedaStub(object):
    """Definicion del servicio de busqueda
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerRespuesta = channel.unary_unary(
                '/search.ServicioBusqueda/ObtenerRespuesta',
                request_serializer=protoBusqueda__pb2.Nombre.SerializeToString,
                response_deserializer=protoBusqueda__pb2.ListaResultante.FromString,
                )


class ServicioBusquedaServicer(object):
    """Definicion del servicio de busqueda
    """

    def ObtenerRespuesta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioBusquedaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerRespuesta': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerRespuesta,
                    request_deserializer=protoBusqueda__pb2.Nombre.FromString,
                    response_serializer=protoBusqueda__pb2.ListaResultante.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.ServicioBusqueda', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServicioBusqueda(object):
    """Definicion del servicio de busqueda
    """

    @staticmethod
    def ObtenerRespuesta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search.ServicioBusqueda/ObtenerRespuesta',
            protoBusqueda__pb2.Nombre.SerializeToString,
            protoBusqueda__pb2.ListaResultante.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
