# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoBusqueda.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoBusqueda.proto',
  package='search',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13protoBusqueda.proto\x12\x06search\"\x18\n\x06Nombre\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"-\n\x0fListaResultante\x12\x1a\n\x04item\x18\x01 \x03(\x0b\x32\x0c.search.Item\"A\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05marca\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x05\x32Q\n\x10ServicioBusqueda\x12=\n\x10ObtenerRespuesta\x12\x0e.search.Nombre\x1a\x17.search.ListaResultante\"\x00\x62\x06proto3'
)




_NOMBRE = _descriptor.Descriptor(
  name='Nombre',
  full_name='search.Nombre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='search.Nombre.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=55,
)


_LISTARESULTANTE = _descriptor.Descriptor(
  name='ListaResultante',
  full_name='search.ListaResultante',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='search.ListaResultante.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=102,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='search.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='search.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='search.Item.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marca', full_name='search.Item.marca', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='precio', full_name='search.Item.precio', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=169,
)

_LISTARESULTANTE.fields_by_name['item'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['Nombre'] = _NOMBRE
DESCRIPTOR.message_types_by_name['ListaResultante'] = _LISTARESULTANTE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nombre = _reflection.GeneratedProtocolMessageType('Nombre', (_message.Message,), {
  'DESCRIPTOR' : _NOMBRE,
  '__module__' : 'protoBusqueda_pb2'
  # @@protoc_insertion_point(class_scope:search.Nombre)
  })
_sym_db.RegisterMessage(Nombre)

ListaResultante = _reflection.GeneratedProtocolMessageType('ListaResultante', (_message.Message,), {
  'DESCRIPTOR' : _LISTARESULTANTE,
  '__module__' : 'protoBusqueda_pb2'
  # @@protoc_insertion_point(class_scope:search.ListaResultante)
  })
_sym_db.RegisterMessage(ListaResultante)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'protoBusqueda_pb2'
  # @@protoc_insertion_point(class_scope:search.Item)
  })
_sym_db.RegisterMessage(Item)



_SERVICIOBUSQUEDA = _descriptor.ServiceDescriptor(
  name='ServicioBusqueda',
  full_name='search.ServicioBusqueda',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=171,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='ObtenerRespuesta',
    full_name='search.ServicioBusqueda.ObtenerRespuesta',
    index=0,
    containing_service=None,
    input_type=_NOMBRE,
    output_type=_LISTARESULTANTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICIOBUSQUEDA)

DESCRIPTOR.services_by_name['ServicioBusqueda'] = _SERVICIOBUSQUEDA

# @@protoc_insertion_point(module_scope)
